In [2]:
#8.3 Project Presentations for WASHSTL201809DATA3 by Group H - Cody Braun, Austen Manser and Bill Nash

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
top100df = pd.read_csv("../Resources/Feature_MergedDF.csv")
top100df.head()

,Title,Artist,Peak_Position_x,Song ID,Song Popularity,Acousticness,Danceability,Energy,Liveness,Speechiness,Valence,Tempo,Instrumentalness,Loudness,Date
0,"""Yep!""",Duane Eddy His Twangy Guitar And The Rebels,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1959-03-25
1,'Til,The Angels,14,4xDL1E4h0s3gHADCG7EQBd,0.0,0.7250,0.508,0.368,0.133,0.0248,0.337,90.043,0.818,-7.697,1961-10-11
2,('til) I Kissed You,The Everly Brothers,4,0hA25gRi0Gh56Lb1wrud2Q,0.0,0.0231,0.704,0.686,0.183,0.0284,0.579,138.562,0.000,-8.509,1959-08-12
3,(A Ship Will Come) Ein Schiff Wird Kommen,Lale Anderson,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1961-04-19
4,(All of a Sudden) My Heart Sings,Paul Anka,15,5Eeq19q3Ft77GpSENEZL2I,23.0,0.8090,0.307,0.267,0.269,0.0327,0.390,111.322,0.000,-11.898,1958-12-17

In [4]:
top100filteredDF = top100df.dropna()
top100filteredDF.head()
len(top100filteredDF)

20950

In [6]:
top100not1df = top100filteredDF.loc[top100filteredDF["Peak_Position_x"]>1,:]
len(top100not1df)

20040

In [18]:
years = []
years = [x[:3]+"0" for x in top100not1df["Date"]]
#print(years)
top100not1df["Year"] = years
top100not1df.head()

C:\Users\codyb\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Title,Artist,Peak_Position_x,Song ID,Song Popularity,Acousticness,Danceability,Energy,Liveness,Speechiness,Valence,Tempo,Instrumentalness,Loudness,Date,Year
1,'Til,The Angels,14,4xDL1E4h0s3gHADCG7EQBd,0.0,0.7250,0.508,0.368,0.133,0.0248,0.337,90.043,0.818000,-7.697,1961-10-11,1960
2,('til) I Kissed You,The Everly Brothers,4,0hA25gRi0Gh56Lb1wrud2Q,0.0,0.0231,0.704,0.686,0.183,0.0284,0.579,138.562,0.000000,-8.509,1959-08-12,1950
4,(All of a Sudden) My Heart Sings,Paul Anka,15,5Eeq19q3Ft77GpSENEZL2I,23.0,0.8090,0.307,0.267,0.269,0.0327,0.390,111.322,0.000000,-11.898,1958-12-17,1950
5,(Baby) Hully Gully,The Olympics,72,0y5gB4JoCqvHeMoVbK6GZh,0.0,0.5910,0.662,0.739,0.374,0.0310,0.954,116.167,0.000023,-5.844,1960-01-27,1960
6,(Dance The) Mess Around,Chubby Checker,24,0w6KXM33lFxPhNH46VFeno,0.0,0.0783,0.541,0.594,0.205,0.0979,0.743,141.885,0.000000,-11.422,1961-04-19,1960

In [19]:
top100not1df.to_csv("../Resources/Top100Not1_withDecade.csv", index=False, encoding="UTF-8")